### ISSUE TITLE
Authorization Subjects

### ISSUE THREAD

**Issue by Eunovo** [Eunovo/superbackend#11]
Currently, we can only give permissions to user roles. This might work for simple apps but a more advanced approach is needed for larger apps.

I'd like to extend Authorization Subjects(targets that can hold permissions) to include developer-defined classes like 'owner', 'blocked', 'collaborator', 'member' e.t.c and specific user handles like usernames, ids, e.t.c. These user-defined classes are not roles, for example, an admin can be an 'owner' or 'blocked' to a resource. With this, we can assign permissions to a broad category of users not just on roles but on what they are to a resource, like an 'owner'.

Several challenges are present here;

- How do we know that a particular Principal falls under an 'owner' class for a particular resource?
- How do we handle relationships?

For example, imagine an online store with three models; 'User', 'Store' and 'Product'.  A user creates a store so he becomes an 'owner' to that store and this gives him certain permissions. Now, a user wants to create a product for a store, and we only allow store owners to create products for stores.

How do we authorise such a user to create this product?

We need to check that the user is the 'owner' of the store. This would require one DB call. What if we had to pull three different documents across different collections? More DB calls? In relational databases, it should be possible to solve this with a clever join query. For NoSQL databases, we can use [aggregate](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/) but this [creates problems for shared collections](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/#lookup-sharded-collections) or we can just use [embedded data models](https://docs.mongodb.com/manual/core/data-model-design/#data-modeling-embedding)

Can we create a solution that chooses the optimal approach depending on the DB?
These solutions sometimes depend on data modelling which is done by the developer. Maybe we should focus on allowing the dev to architect his authorization approach.

WDYT @mikkybang ?

**Comment by mikkybang** [comment]
@Eunovo For the Relationship part, I think we can simply check for ownership in the first level then force the next level to use the foreign key from the first check.
i.e we do not have to check whether a user owns a product, we just have to check that the user owns the store... to create a product owned by the user, we get the user's store, the manually form the relationship between the user's store and the product
